### ISSUE TITLE
Set up continuous integration

### ISSUE THREAD

**Issue by aliascash** [aliascash/alias-wallet-archive#11]
Travis CI is a hosted, distributed continuous integration service used to build and test software projects hosted at GitHub. We need to set up XSPEC to use Travis or consider AppVeyor for same to ensure build quality.

**Comment by dorsegal** [comment]
I can try and help with Travis. I have knowledge with Jenkins but I think they are pretty much the same

**Comment by aliascash** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Set up CI w/ Travis / AppVeyor](https://trello.com/c/fZHBtMHz/6-set-up-ci-w-travis-appveyor)

**Comment by HLXEasy** [comment]
https://ci.spectreproject.io/
