### ISSUE TITLE
HD Wallet as Default

### ISSUE THREAD

**Issue by dynamiccreator** [aliascash/alias-wallet-archive#115]
I would strongly recommend to make HD wallet the default wallet, so that you can't loose your coins when you're wallet.dat is corrupted or has gone.
If somebody has imported addresses additionally, a warning exclamation mark along with a tooltip info should light up.The info should say, that it is highly recommended to send the coins to a address created by the HD wallet.

**Comment by teknex** [comment]
Redundant to #82
