### ISSUE TITLE
Improve the translation to use signals and slots and be asnycrounos 

### ISSUE THREAD

**Issue by shbli** [aliascash/alias-wallet-archive#14]
While moving to the QtWebEngine, the functionality of synchronous function calls from/to JavaScript/C++ is not supported anymore duo to the nature of the QtWebEngine (vs the old QtWebKit)

I have disabled the translation feature temporary. It should not be that difficult to work on it. here is the commit

https://github.com/spectrecoin/spectre/commit/c0689787dfa79b2669208ef46da750b688255f3e#diff-16947ee12ad2c05f9e6490fd78e989df

The code is located at src/qt/res/assets/js/spectre.min.js

**Comment by shbli** [comment]
if you are good at Javascript/Web/Qt signals and slots you can solve this one pretty easily.

**Comment by HLXEasy** [comment]
Resolved with release 4.4.0
