### ISSUE TITLE
Spectre.app (Mac OSX & Win) wants to connect to IPv4 addresses when starting

### ISSUE THREAD

**Issue by aliascash** [aliascash/alias-wallet-archive#16]
I am running a filter software called Little Snitch Mac OSX and when I start the Spectre.app it wants to connect to IPv4 address: 188.40.128.246 - see screen shot. This appears to be a random German IP. Why does the Spectre.app want to connect to an IPv4 address when the network is .onion only under Tor.

http://www.infosniper.net/index.php?ip_address=188.40.128.246&k=&map_source=1&overview_map=1&lang=1&map_type=1&zoom_level=7
<img width="722" alt="screen shot 2018-05-07 at 18 56 53" src="https://user-images.githubusercontent.com/22733129/39717042-feb0109e-5229-11e8-8ee4-085e034d6842.png">

**Comment by aliascash** [comment]
<img width="304" alt="screen shot 2018-05-07 at 19 18 08" src="https://user-images.githubusercontent.com/22733129/39717526-6ed24328-522b-11e8-9757-f7e29996a016.png">

**Comment by aliascash** [comment]
When I block one IPv4 address the Spectre.app immediately connects to another
<img width="279" alt="screen shot 2018-05-07 at 19 19 09" src="https://user-images.githubusercontent.com/22733129/39717574-a6dd8fd4-522b-11e8-9f0c-faeb5dbbbb1d.png">

**Comment by elamoeba** [comment]
I'm fairly certain these addresses are part of the Tor network.
If you Google "178.254.19.112" it shows up on TorStatus.
