### ISSUE TITLE
1.4.0-alpha crash on startup

### ISSUE THREAD

**Issue by teknex** [aliascash/alias-wallet-archive#17]
crashes on startup (window never opens). Spectre1.4.0alpha-win\debug.log output:
```
[0510/000003.763:WARNING:resource_bundle_qt.cpp(115)] locale_file_path.empty() for locale 
```
Startup messages:
```
App start in main.cpp
Failed to load libEGL (Das angegebene Modul wurde nicht gefunden.)
QWindowsEGLStaticContext::create: Failed to load and resolve libEGL functions
Failed to load opengl32sw.dll (Das angegebene Modul wurde nicht gefunden.)
Failed to load and resolve WGL/OpenGL functions
Failed to load libEGL (Das angegebene Modul wurde nicht gefunden.)
QWindowsEGLStaticContext::create: Failed to load and resolve libEGL functions
Failed to load opengl32sw.dll (Das angegebene Modul wurde nicht gefunden.)
Failed to load and resolve WGL/OpenGL functions
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
Qt WebEngine ICU data not found at C:/D/QtSDK/5.10.1/msvc2017_64/resources. Trying parent directory...
Qt WebEngine ICU data not found at C:/D/QtSDK/5.10.1/msvc2017_64. Trying application directory...
Installed Qt WebEngine locales directory not found at location C:/D/QtSDK/5.10.1/msvc2017_64/translations\qtwebengine_locales. Trying application directory...
Qt WebEngine locales directory not found at location C:/Blockchain/Spectre/Spectre1.4.0alpha-win\qtwebengine_locales. Trying fallback directory... Translations MAY NOT not be correct.
Qt WebEngine resources not found at C:/D/QtSDK/5.10.1/msvc2017_64/resources. Trying parent directory...
Qt WebEngine resources not found at C:/D/QtSDK/5.10.1/msvc2017_64. Trying application directory...
May 10 00:26:49.723 [notice] Tor 0.3.0.9 running on Windows 8 with Libevent 2.1.8-beta, OpenSSL 1.1.0f, Zlib 1.2.11, Liblzma N/A, and Libzstd N/A.
May 10 00:26:49.723 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
May 10 00:26:49.728 [notice] Configuration file "C:\Users\phili\AppData\Roaming\SpectreCoin\tor\torrc" not present, using reasonable defaults.
May 10 00:26:49.729 [notice] Scheduler type KISTLite has been enabled.
May 10 00:26:49.729 [notice] Opening Socks listener on 127.0.0.1:9089
Loading addresses from .onion seeds
3 addresses found from .onion seeds
Failed to load libEGL (Das angegebene Modul wurde nicht gefunden.)
QWindowsEGLStaticContext::create: Failed to load and resolve libEGL functions
Failed to load opengl32sw.dll (Das angegebene Modul wurde nicht gefunden.)
Failed to load and resolve WGL/OpenGL functions
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, colorSpace QSurfaceFormat::ColorSpace(DefaultColorSpace), profile  QSurfaceFormat::OpenGLContextProfile(NoProfile)) .
This is most likely caused by not having the necessary graphics drivers installed.

Install a driver providing OpenGL 2.0 or higher, or, if this is not possible, make sure the ANGLE Open GL ES 2.0 emulation libraries (libEGL.dll, libGLESv2.dll and d3dcompiler_*.dll) are available in the application executable's directory or in a location listed in PATH.
```

**Comment by aliascash** [comment]
@teknex can you please download and try the v.1.4.0-beta and see if you have the same issue

**Comment by teknex** [comment]
Still crashing, looks like same problem. Running this on Windows 10 x64 with Nvidea 1080ti:

C:\Blockchain\Spectre\spectre-v1.4.0-beta-Win64>spectre.exe
App start in main.cpp
Failed to load libEGL (Das angegebene Modul wurde nicht gefunden.)
QWindowsEGLStaticContext::create: Failed to load and resolve libEGL functions
Failed to load opengl32sw.dll (Das angegebene Modul wurde nicht gefunden.)
Failed to load and resolve WGL/OpenGL functions
Failed to load libEGL (Das angegebene Modul wurde nicht gefunden.)
QWindowsEGLStaticContext::create: Failed to load and resolve libEGL functions
Failed to load opengl32sw.dll (Das angegebene Modul wurde nicht gefunden.)
Failed to load and resolve WGL/OpenGL functions
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
Qt WebEngine ICU data not found at C:/D/QtSDK/5.10.1/msvc2017_64/resources. Trying parent directory...
Qt WebEngine ICU data not found at C:/D/QtSDK/5.10.1/msvc2017_64. Trying application directory...
Installed Qt WebEngine locales directory not found at location C:/D/QtSDK/5.10.1/msvc2017_64/translations\qtwebengine_locales. Trying application directory...
Qt WebEngine locales directory not found at location C:/Blockchain/Spectre/spectre-v1.4.0-beta-Win64\qtwebengine_locales. Trying fallback directory... Translations MAY NOT not be correct.
Qt WebEngine resources not found at C:/D/QtSDK/5.10.1/msvc2017_64/resources. Trying parent directory...
Qt WebEngine resources not found at C:/D/QtSDK/5.10.1/msvc2017_64. Trying application directory...
May 17 22:58:31.011 [notice] Tor 0.3.0.9 running on Windows 8 with Libevent 2.1.8-beta, OpenSSL 1.1.0f, Zlib 1.2.11, Liblzma N/A, and Libzstd N/A.
May 17 22:58:31.011 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
May 17 22:58:31.015 [notice] Configuration file "C:\Users\phili\AppData\Roaming\SpectreCoin\tor\torrc" not present, using reasonable defaults.
May 17 22:58:31.017 [notice] Scheduler type KISTLite has been enabled.
May 17 22:58:31.017 [notice] Opening Socks listener on 127.0.0.1:9089
Loading addresses from .onion seeds
3 addresses found from .onion seeds
Failed to load libEGL (Das angegebene Modul wurde nicht gefunden.)
QWindowsEGLStaticContext::create: Failed to load and resolve libEGL functions
Failed to load opengl32sw.dll (Das angegebene Modul wurde nicht gefunden.)
Failed to load and resolve WGL/OpenGL functions
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, colorSpace QSurfaceFormat::ColorSpace(DefaultColorSpace), profile  QSurfaceFormat::OpenGLContextProfile(NoProfile)) .
This is most likely caused by not having the necessary graphics drivers installed.

Install a driver providing OpenGL 2.0 or higher, or, if this is not possible, make sure the ANGLE Open GL ES 2.0 emulation libraries (libEGL.dll, libGLESv2.dll and d3dcompiler_*.dll) are available in the application executable's directory or in a location listed in PATH.

**Comment by shbli** [comment]
@teknex Could you please download the following 3 dlls that are missing

https://ufile.io/bu75x

Put them in the same folder next to spectre.exe and try again. Let us know how this works for you.

If it fix it we will make sure to ship the new version with it and also update our build instructions to make sure they're always available.

**Comment by teknex** [comment]
I tested as instructed. Still not working. Nvideas driver I am using is
supporting OpenGL 2.0:

App start in main.cpp
QWindowsEGLStaticContext::create: Could not initialize EGL display: error
0x3003
Failed to load opengl32sw.dll (Das angegebene Modul wurde nicht gefunden.)
Failed to load and resolve WGL/OpenGL functions
QWindowsEGLStaticContext::create: Could not initialize EGL display: error
0x3003
Failed to load opengl32sw.dll (Das angegebene Modul wurde nicht gefunden.)
Failed to load and resolve WGL/OpenGL functions
WebEngineContext used before QtWebEngine::initialize() or OpenGL context
creation failed.
Qt WebEngine ICU data not found at C:/D/QtSDK/5.10.1/msvc2017_64/resources.
Trying parent directory...
Qt WebEngine ICU data not found at C:/D/QtSDK/5.10.1/msvc2017_64. Trying
application directory...
Installed Qt WebEngine locales directory not found at location
C:/D/QtSDK/5.10.1/msvc2017_64/translations\qtwebengine_locales. Trying
application directory...
Qt WebEngine locales directory not found at location
C:/Blockchain/Spectre/spectre-v1.4.0-beta-Win64\qtwebengine_locales. Trying
fallback directory... Translations MAY NOT not be correct.
Qt WebEngine resources not found at
C:/D/QtSDK/5.10.1/msvc2017_64/resources. Trying parent directory...
Qt WebEngine resources not found at C:/D/QtSDK/5.10.1/msvc2017_64. Trying
application directory...
May 19 00:47:49.076 [notice] Tor 0.3.0.9 running on Windows 8 with Libevent
2.1.8-beta, OpenSSL 1.1.0f, Zlib 1.2.11, Liblzma N/A, and Libzstd N/A.
May 19 00:47:49.076 [notice] Tor can't help you if you use it wrong! Learn
how to be safe at https://www.torproject.org/download/download#warning
May 19 00:47:49.080 [notice] Configuration file
"C:\Users\phili\AppData\Roaming\SpectreCoin\tor\torrc" not present, using
reasonable defaults.
May 19 00:47:49.082 [notice] Scheduler type KISTLite has been enabled.
May 19 00:47:49.082 [notice] Opening Socks listener on 127.0.0.1:9089
Loading addresses from .onion seeds
3 addresses found from .onion seeds
QWindowsEGLStaticContext::create: Could not initialize EGL display: error
0x3003
Failed to load opengl32sw.dll (Das angegebene Modul wurde nicht gefunden.)
Failed to load and resolve WGL/OpenGL functions
Failed to create OpenGL context for format QSurfaceFormat(version 2.0,
options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24,
redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize
-1, stencilBufferSize 8, samples 0, swapBehavior
QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1,
colorSpace QSurfaceFormat::ColorSpace(DefaultColorSpace), profile
QSurfaceFormat::OpenGLContextProfile(NoProfile)) .
This is most likely caused by not having the necessary graphics drivers
installed.

Install a driver providing OpenGL 2.0 or higher, or, if this is not
possible, make sure the ANGLE Open GL ES 2.0 emulation libraries
(libEGL.dll, libGLESv2.dll and d3dcompiler_*.dll) are available in the
application executable's directory or in a location listed in PATH.

**Comment by shbli** [comment]
Hey

This may help providing more details about the issue you are facing (Someone with similar problem)

https://github.com/ContinuumIO/anaconda-issues/issues/9142

If that does not help I'll get back to you again later there's quit few things I'm working on right now but we defiantly want to get back to this one.

If you in fact are able to solver it let me know how it goes so we can fix it in the next beta version

**Comment by teknex** [comment]
Hey Ahmed

Problem vanished. Reason not clear.

I put the file 'opengl32.dll' in the spectre folder, and could succesfully
start spectre. Afterwards I deleted the dll to verify the dll was the
reason, but now it still works.
Anyway this bug can probably be closed.

Now I have the 'crash on unlock' problem. Hope you can fix that soon.

Thank you

Tek

**Comment by shbli** [comment]
@teknex Thank you for this. Might be of some Windows updates. By the way planning to go to Qt 5.11 instead of 5.10.

For the wallet crash when unlocking. We are able to work on this but for now there's something else. I estimate hopefully soon by the end of this weekend.

**Comment by aliascash** [comment]
@shbli can this be closed?

**Comment by shbli** [comment]
@spectrecoin @teknex thank you yes closed and now if it happens again try to reopen it.
