### ISSUE TITLE
Tor process is not cleanly shutting down when closing the Qt wallet

### ISSUE THREAD

**Issue by bitcoinx2** [aliascash/alias-wallet-archive#173]
On Fedora 29, I noticed that the Tor child process does not exit when closing the Qt wallet, which makes it necessary to kill the Tor process manually. The problem does not happen with `spectrecoind`, only with the graphical wallet.

**Comment by dynamiccreator** [comment]
Same here on Ubuntu / Linux Mint. need to shut down the process manually to reopen it, after quitting.

**Comment by dynamiccreator** [comment]
I need to add that it also happens with spectrecoind. The process itself (spectrecoind) and the sub process "tor" keeps running after closing the console.

**Comment by HLXEasy** [comment]
Fixed with release 3.0.10
