### ISSUE TITLE
tooltip for public->stealth transfer

### ISSUE THREAD

**Issue by dynamiccreator** [aliascash/alias-wallet-archive#178]
Please make a tool tip for the spectre->xspec transfer, because it is not clear to which address the transfer will go, because it will be created afterwards.

**Comment by teknex** [comment]
With 3.0.9 there will be the following explanation for the Pay To tooltip:
The stealth address to transfer the balance to.<br>Only <b>owned</b> stealth addresses can be used for XSPEC-SPECTRE transfers.<br>SPECTRE to XSPEC transfers create <b>new one-time</b> XSPEC addresses (visible in <b>Coin Control</b> dialog).
