### ISSUE TITLE
1.4.0 Beta (Windows 10 64-bit) crash on unlocking wallet

### ISSUE THREAD

**Issue by ptownsimon** [aliascash/alias-wallet-archive#18]
Hope this is useful.

**From Windows Command Line:**

C:\Spectre1.4.0alpha-win>spectre
App start in main.cpp
Qt WebEngine ICU data not found at C:/D/QtSDK/5.10.1/msvc2017_64/resources. Trying parent directory...
Qt WebEngine ICU data not found at C:/D/QtSDK/5.10.1/msvc2017_64. Trying application directory...
Installed Qt WebEngine locales directory not found at location C:/D/QtSDK/5.10.1/msvc2017_64/translations\qtwebengine_locales. Trying application directory...
Qt WebEngine locales directory not found at location C:/Spectre1.4.0alpha-win\qtwebengine_locales. Trying fallback directory... Translations MAY NOT not be correct.
Qt WebEngine resources not found at C:/D/QtSDK/5.10.1/msvc2017_64/resources. Trying parent directory...
Qt WebEngine resources not found at C:/D/QtSDK/5.10.1/msvc2017_64. Trying application directory...
May 09 ##.##.##.### [notice] Tor 0.3.0.9 running on Windows 8 with Libevent 2.1.8-beta, OpenSSL 1.1.0f, Zlib 1.2.11, Liblzma N/A, and Libzstd N/A.
May 09 ##.##.##.### [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
May 09 ##.##.##.### [notice] Configuration file "C:\Users\*****\AppData\Roaming\SpectreCoin\tor\torrc" not present, using reasonable defaults.
May 09 ##.##.##.### [notice] Scheduler type KISTLite has been enabled.
May 09 ##.##.##.### [notice] Opening Socks listener on 127.0.0.1:9089
Loading addresses from .onion seeds
3 addresses found from .onion seeds
js: Uncaught TypeError: Cannot read property 'classList' of null
js: Uncaught TypeError: Cannot read property 'classList' of null
js: Uncaught TypeError: Cannot read property 'classList' of null
js: Uncaught TypeError: Cannot read property 'classList' of null
js: Uncaught TypeError: Cannot read property 'classList' of null
js: Uncaught TypeError: Cannot read property 'classList' of null
js: Uncaught TypeError: Cannot read property 'classList' of null
js: Uncaught TypeError: Cannot read property 'classList' of null

**From debug.txt**

SpectreCoin version v1.4.0.0-g ($Format:%cD)
Operating in full mode.
Using OpenSSL version OpenSSL 1.1.0f  25 May 2017
Startup time: 05/09/18 23:19:58
Default data directory C:\Users\user\AppData\Roaming\SpectreCoin
Used data directory C:\Users\user\AppData\Roaming\SpectreCoin
db version is Berkeley DB 4.8.30: (April 12, 2010)
dbenv.open LogDir=C:\Users\user\AppData\Roaming\SpectreCoin\database ErrorFile=C:\Users\user\AppData\Roaming\SpectreCoin\db.log
Bound to 127.0.0.1:37347
AddLocal(qz43oqeux5ehhutf.onion:37347,4)
Loading block index...
Opening LevelDB in C:\Users\user\AppData\Roaming\SpectreCoin\txleveldb
Opened LevelDB successfully
Transaction index version is 70511
LoadBlockIndex(): hashBestChain=c7b71dfb4675b8caea5e6830e2e0369f6c09a09f4251bd900b2b5b5e532070c6  height=665495  trust=1517464136623456867714  date=05/09/18 23:00:00
Verifying last 2500 blocks at level 1
 block index            7631ms
Loading wallet...
nFileVersion = 1040000
Keys: 0 plaintext, 100 encrypted, 100 w/ metadata, 100 total
Loading master ext key.
Loading ext accounts.
Loading ext account packs.
 wallet                   73ms
Loading addresses...
Loaded 1513 addresses from peers.dat  6ms
Secure messaging starting.
Loaded 1 addresses.
Loaded addresses from SMSG.ini
Processed 0 files, loaded 0 buckets containing 0 messages.
smsg thread start
smsg-pow thread start
mapBlockIndex.size() = 671501
mapBlockThinIndex.size() = 0
nBestHeight = 665495
setKeyPool.size() = 100
mapWallet.size() = 93
mapAddressBook.size() = 2
onionseed thread start
net thread start
onionseed thread exit
addcon thread start
opencon thread start
msghand thread start
dumpaddr thread start
wflush thread start
miner thread start
Done loading.
Network: main, port: 37347
SOCKS5 connecting q5swjsvghrxft5ew.onion
SOCKS5 connected q5swjsvghrxft5ew.onion
SOCKS5 connecting anffhnthjspov44p.onion
Added time data, samples 2, offset -88 (-1 minutes)
Received mblk 14
SetBestChain: new best=b7f1d145a1ea9db6c148b8d9dc4cfaa0c75472a1d874c0e4ce4e390087e64061  height=665496  trust=1517466947647914733682  blocktrust=2811024457865968  date=05/09/18 23:04:00
ProcessBlock: ACCEPTED b7f1d145a1ea9db6c148
SetBestChain: new best=bee4ffe071c8be23632afae209758c4c8ddda9f45e7d532ba9ffd04b035e3b7c  height=665497  trust=1517469747275183470903  blocktrust=2799627268737221  date=05/09/18 23:04:32
ProcessBlock: ACCEPTED bee4ffe071c8be23632a
SetBestChain: new best=6096d1828f1126757a66b893702d04a851182fc15a6f5c617b4acac5ebaf66b7  height=665498  trust=1517472548977006850212  blocktrust=2801701823379309  date=05/09/18 23:05:20
ProcessBlock: ACCEPTED 6096d1828f1126757a66
SetBestChain: new best=dfd4012bd1fdcd9efa0b0b00ab2e0397f188946f741fcfb93d064ac13ba4215a  height=665499  trust=1517475351716429211182  blocktrust=2802739422360970  date=05/09/18 23:05:36
ProcessBlock: ACCEPTED dfd4012bd1fdcd9efa0b
SetBestChain: new best=2d588c5e47d7e02816c82096b4b36b10e799046d4a530a73b23f7ca03c3ee5a3  height=665500  trust=1517478157571597757173  blocktrust=2805855168545991  date=05/09/18 23:06:24
ProcessBlock: ACCEPTED 2d588c5e47d7e02816c8
SetBestChain: new best=1cf29ebacd20231515b599c12efac0bd6e6c1949c29812ef0544c005c4d93da8  height=665501  trust=1517480964465776114646  blocktrust=2806894178357473  date=05/09/18 23:06:40
ProcessBlock: ACCEPTED 1cf29ebacd20231515b5
SetBestChain: new best=89586d037c803bb611027a615b3df099bd1583ba9ddfae8aa8907272ac7f8598  height=665502  trust=1517483774479933910488  blocktrust=2810014157795842  date=05/09/18 23:06:56
ProcessBlock: ACCEPTED 89586d037c803bb61102
SetBestChain: new best=158ca0122b4a79b745f8e8d4233fa21dda1565e787158b9e9b90d0f15575211c  height=665503  trust=1517486587617663231417  blocktrust=2813137729320929  date=05/09/18 23:09:36
ProcessBlock: ACCEPTED 158ca0122b4a79b745f8
SetBestChain: new best=f660a0d4c40a367d2d4e6a18dd8a14fd4b160629c786363b8340cf2c8e3b1611  height=665504  trust=1517489394523520228014  blocktrust=2806905856996597  date=05/09/18 23:10:24
ProcessBlock: ACCEPTED f660a0d4c40a367d2d4e
SetBestChain: new best=7c84677c479b09e3d137d684be2eba7d8584ed2bf43e27c2f828b84ab5c2980c  height=665505  trust=1517492202469165467063  blocktrust=2807945645239049  date=05/09/18 23:10:56
ProcessBlock: ACCEPTED 7c84677c479b09e3d137
SetBestChain: new best=1392eab47ad7a479ac0a1c559eba70a6e8f41dd09e10b15ca47b0ff8338ef91c  height=665506  trust=1517495012495027879097  blocktrust=2810025862412034  date=05/09/18 23:12:00
ProcessBlock: ACCEPTED 1392eab47ad7a479ac0a
SetBestChain: new best=e83606f43e23dfa701f74b84a18cc04dfc6fbbdbec6deacf3888eb8c80f14463  height=665507  trust=1517497822520890291131  blocktrust=2810025862412034  date=05/09/18 23:13:52
ProcessBlock: ACCEPTED e83606f43e23dfa701f7
SetBestChain: new best=974ffdb59d5fab39cc53aef598004f5b2eb163cfd6b4901c30391bbaac6c7c75  height=665508  trust=1517500629431752448531  blocktrust=2806910862157400  date=05/09/18 23:14:08
ProcessBlock: ACCEPTED 974ffdb59d5fab39cc53
ERROR: Proxy error: host unreachable
SOCKS5 connecting lh7z4b5xkhketbfn.onion
SetBestChain: new best=0c26cc51975858f6cb70d070223bdfe5eb59235c9b1904433d785ebcf2e301a3  height=665509  trust=1517503439462631154496  blocktrust=2810030878705965  date=05/09/18 23:17:20
ProcessBlock: ACCEPTED 0c26cc51975858f6cb70
Flushing wallet.dat
Flushed wallet.dat 37ms
SOCKS5 connected lh7z4b5xkhketbfn.onion
SOCKS5 connecting pioz3uv3i3s3vqhx.onion
Added time data, samples 3, offset -65 (-1 minutes)
SOCKS5 connected pioz3uv3i3s3vqhx.onion
SOCKS5 connecting gxrtaufzsmqarlmp.onion
Added time data, samples 4, offset -86 (-1 minutes)
SOCKS5 connected gxrtaufzsmqarlmp.onion
SOCKS5 connecting twvqjtcmdi2lw6kp.onion
Added time data, samples 5, offset -100 (-1 minutes)
nTimeOffset = -86  (-1 minutes)
Unlocking wallet.

**Comment by aliascash** [comment]
@ptownsimon can you please download and try the v.1.4.0-beta and see if you have the same issue

**Comment by ptownsimon** [comment]
1.4.0 Beta on Windows 10 64-bit still crashing upon unlocking wallet for staking
Looks like it's missing some Qt5SDK files from the wallet download.

**From Command Line:**

App start in main.cpp
Qt WebEngine ICU data not found at C:/D/QtSDK/5.10.1/msvc2017_64/resources. Trying parent directory...
Qt WebEngine ICU data not found at C:/D/QtSDK/5.10.1/msvc2017_64. Trying application directory...
Installed Qt WebEngine locales directory not found at location C:/D/QtSDK/5.10.1/msvc2017_64/translations\qtwebengine_locales. Trying application directory...
Qt WebEngine locales directory not found at location C:/spectre-v1.4.0-beta-Win64\qtwebengine_locales. Trying fallback directory... Translations MAY NOT not be correct.
Qt WebEngine resources not found at C:/D/QtSDK/5.10.1/msvc2017_64/resources. Trying parent directory...
Qt WebEngine resources not found at C:/D/QtSDK/5.10.1/msvc2017_64. Trying application directory...
May 17 09:51:19.240 [notice] Tor 0.3.0.9 running on Windows 8 with Libevent 2.1.8-beta, OpenSSL 1.1.0f, Zlib 1.2.11, Liblzma N/A, and Libzstd N/A.
May 17 09:51:19.240 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
May 17 09:51:19.242 [notice] Configuration file "C:\Users\user\AppData\Roaming\SpectreCoin\tor\torrc" not present, using reasonable defaults.
May 17 09:51:19.247 [notice] Scheduler type KISTLite has been enabled.
May 17 09:51:19.247 [notice] Opening Socks listener on 127.0.0.1:9089
Loading addresses from .onion seeds
3 addresses found from .onion seeds
js: Uncaught TypeError: Cannot read property 'setAttribute' of null
js: Uncaught TypeError: Cannot read property 'classList' of null
js: Uncaught TypeError: Cannot read property 'classList' of null
js: Uncaught TypeError: Cannot read property 'classList' of null
js: Uncaught TypeError: Cannot read property 'classList' of null
js: Uncaught TypeError: Cannot read property 'classList' of null
js: Uncaught TypeError: Cannot read property 'classList' of null
js: Uncaught TypeError: Cannot read property 'classList' of null
js: Uncaught TypeError: Cannot read property 'classList' of null

**From debug.txt**

SpectreCoin version v1.4.0.0-g ($Format:%cD)
Operating in full mode.
Using OpenSSL version OpenSSL 1.1.0f  25 May 2017
Startup time: 05/17/18 15:51:19
Default data directory C:\Users\user\AppData\Roaming\SpectreCoin
Used data directory C:\Users\user\AppData\Roaming\SpectreCoin
db version is Berkeley DB 4.8.30: (April 12, 2010)
dbenv.open LogDir=C:\Users\user\AppData\Roaming\SpectreCoin\database ErrorFile=C:\Users\user\AppData\Roaming\SpectreCoin\db.log
Bound to 127.0.0.1:37347
AddLocal(qz43oqeux5ehhutf.onion:37347,4)
Loading block index...
Opening LevelDB in C:\Users\user\AppData\Roaming\SpectreCoin\txleveldb
Opened LevelDB successfully
Transaction index version is 70511
LoadBlockIndex(): hashBestChain=14b268d997393ef041f33f5adf2bd43df7e5bb5e8eaa91d296fa2a05bf0ee69e  height=675935  trust=1547070740169473797110  date=05/17/18 15:37:04
Verifying last 2500 blocks at level 1
 block index           12795ms
Loading wallet...
nFileVersion = 1040000
Keys: 0 plaintext, 100 encrypted, 100 w/ metadata, 100 total
Loading master ext key.
Loading ext accounts.
Loading ext account packs.
 wallet                   49ms
Loading addresses...
Loaded 1604 addresses from peers.dat  4ms
Secure messaging starting.
Loaded 1 addresses.
Loaded addresses from SMSG.ini
Processed 2 files, loaded 2 buckets containing 2 messages.
smsg thread start
smsg-pow thread start
mapBlockIndex.size() = 682863
mapBlockThinIndex.size() = 0
nBestHeight = 675935
setKeyPool.size() = 100
mapWallet.size() = 110
mapAddressBook.size() = 2
onionseed thread start
addcon thread start
onionseed thread exit
opencon thread start
net thread start
msghand thread start
dumpaddr thread start
wflush thread start
miner thread start
Done loading.
Network: main, port: 37347
SOCKS5 connecting 3pwc6nwcrdtvdqjy.onion
SOCKS5 connected 3pwc6nwcrdtvdqjy.onion
SOCKS5 connecting gr4d2vnpujye6mqk.onion
SOCKS5 connected gr4d2vnpujye6mqk.onion
SOCKS5 connecting nokrnebmqkr2ys64.onion
Added time data, samples 2, offset -62 (-1 minutes)
Received mblk 8
SetBestChain: new best=8d7dd3cf0e8ff560b5c56cb0526c89a2fcc0d06a6ad57aff3be9dfdef5ed2555  height=675936  trust=1547073823143132719279  blocktrust=3082973658922169  date=05/17/18 15:40:32
ProcessBlock: ACCEPTED 8d7dd3cf0e8ff560b5c5
SetBestChain: new best=b96a98e18e66afb7d4bb687a3bdcb1843b1548b5a52ba31d78642a86d34b80aa  height=675937  trust=1547076895882065093455  blocktrust=3072738932374176  date=05/17/18 15:41:36
ProcessBlock: ACCEPTED b96a98e18e66afb7d4bb
SetBestChain: new best=378d9b0e0e1a6bce419dc36374919230fa30189c8e033cad81b6736f0051dab1  height=675938  trust=1547079968620997467631  blocktrust=3072738932374176  date=05/17/18 15:41:52
ProcessBlock: ACCEPTED 378d9b0e0e1a6bce419d
SetBestChain: new best=08bf023495a686e40b2d588c2927607b36ff4f5be72ce27554732470f1559ff5  height=675939  trust=1547083044776637345405  blocktrust=3076155639877774  date=05/17/18 15:43:28
ProcessBlock: ACCEPTED 08bf023495a686e40b2d
SetBestChain: new best=5eea90e051386a0d9a7b15ab31b11c86aca7f8a6ec610176d11e282f2b80d6d3  height=675940  trust=1547086118657630277488  blocktrust=3073880992932083  date=05/17/18 15:45:36
ProcessBlock: ACCEPTED 5eea90e051386a0d9a7b
SOCKS5 connected nokrnebmqkr2ys64.onion
SetBestChain: new best=848ad1db3412272fd920fe791ca6f756f34cfc22630fc996fefee53749186058  height=675941  trust=1547089187995416385324  blocktrust=3069337786107836  date=05/17/18 15:48:00
ProcessBlock: ACCEPTED 848ad1db3412272fd920
SetBestChain: new best=7c01e42ffd30286fe18d36726c02b9516d6cd0cf346de7892f93033a820e05cc  height=675942  trust=1547092251664100601936  blocktrust=3063668684216612  date=05/17/18 15:49:04
ProcessBlock: ACCEPTED 7c01e42ffd30286fe18d
SetBestChain: new best=7e7e26c1a166c71fc39d3cf5b56be970edf0111a33c36a3c0f51e799e5e2da50  height=675943  trust=1547095315332784818548  blocktrust=3063668684216612  date=05/17/18 15:50:08
ProcessBlock: ACCEPTED 7e7e26c1a166c71fc39d
SOCKS5 connecting w5ivswpdkeniemq4.onion
Added 1 addresses from gr4d2vnpujye6mqk.onion: 781 tried, 824 new
Added time data, samples 3, offset -91 (-1 minutes)
Flushing wallet.dat
Flushed wallet.dat 27ms
SOCKS5 connected w5ivswpdkeniemq4.onion
SOCKS5 connecting yt4u5iw5rvq7dwmc.onion
Added time data, samples 4, offset -85 (-1 minutes)
Unlocking wallet.

**Comment by shbli** [comment]
We are releasing a new build soon. Let us know if that fixes your problem and mark this as fixed then.

Cheers
Shbli

**Comment by aliascash** [comment]
@shbli Can this be closed as the beta-4 wallet doesn't seem to crash on unlocking

**Comment by shbli** [comment]
@spectrecoin yes you can close it if you no one is facing a problem anymore. You can always reopen it later if it happens again.
