### ISSUE TITLE
Give syncing its own thread

### ISSUE THREAD

**Issue by dynamiccreator** [aliascash/alias-wallet-archive#183]
The syncing process should at least have its own thread, because the UI wallet hangs, while syncing.Would be a nice thing for the overall user experience.

Giving it even more threads (if that is technically possible/ not too much effort) would also speed up the syncing process.

**Comment by teknex** [comment]
Syncing is already done in a separate thread. The UI freeze during sync happens because some UI<>Core sync tasks need to lock the core.

**Comment by dynamiccreator** [comment]
Can't this be fixed somehow else? It's not very professional to have this issue going. I don't know any other wallet with this problem.

**Comment by teknex** [comment]
Unfortunately to fix this the complete code for processing the ATXOs must be refactored. One of the problems is that part of the logic which is independent of the wallet is currently run in the part which usually only updates the wallets. We don't have currently enough resource to fix this issue,

**Comment by teknex** [comment]
UI is now much less frozen due to various optimizations
