### ISSUE TITLE
proof of stake attacks covered? Fake stake / spent stake attack

### ISSUE THREAD

**Issue by dynamiccreator** [aliascash/alias-wallet-archive#184]
I know that the team is already aware of the attack vectors for POS described in that paper:
https://medium.com/@dsl_uiuc/fake-stake-attacks-on-chain-based-proof-of-stake-cryptocurrencies-b8b05723f806

I wonder what is the current state of this attacks in spectrecoin , are they already covered?
-Fake stake status  ???
-Spent stake status ???

**Comment by dynamiccreator** [comment]
There is a fix for 1) out there:
https://medium.com/@phoreblockchain/173-projects-use-phores-fake-stake-vulnerability-8ae9671f170a
is spectre fixed?

**Comment by HLXEasy** [comment]
Fixed with release 3.0.10
