### ISSUE TITLE
UI BUG - Wallet shows wrong spectre staking reward

### ISSUE THREAD

**Issue by dynamiccreator** [aliascash/alias-wallet-archive#185]
Sometimes the wallet shows 3.001 instead of 3.0 as the spectre staking reward. Once it evens showed 33 instead of 3. The 33 was also shown in transactions, not just in the overview as in the below image.

![Bildschirmfoto vom 2019-05-20 11-34-23](https://user-images.githubusercontent.com/43098612/58029820-abe9b900-7b1d-11e9-89b1-05730d38a1be.png)

**Comment by dynamiccreator** [comment]
I now know the reason to this problem: The balance doesn't update after I enter the password into the "The wallet contains locked ATXOs for which is depending..." prompt.
After restart, only if I entered the password before, the balance shows up correct.

**Comment by dynamiccreator** [comment]
Enhancement:
If the user is not enter the password for balance correction there should be an permanent warning, that balance/ transactions are not correct. By clicking on this warning, he can then enter the password. Then the balance must update.

**Comment by teknex** [comment]
@dynamiccreator Did you use a backup wallet.dat or did you stake the same wallet on multiple nodes at the same time?
This error occurs only if a running wallet does not have the private spent key unencrypted when processing an incoming owned staking transaction.

**Comment by dynamiccreator** [comment]
This error occurs on a backup wallet (not staking just checking, watching the stake process).

**Comment by teknex** [comment]
Will be fixed with 3.0.11: After unlock of the wallet, wrong shown staking rewards are corrected

**Comment by HLXEasy** [comment]
Fixed with release 3.0.11
