### ISSUE TITLE
Wallet Balance disappears as soon as secure shared memory is activated

### ISSUE THREAD

**Issue by fpspqr** [aliascash/alias-wallet-archive#186]
Symptoms: Wallet (GUI) Show 0.000000 Balance. Despite there beeing confirmed transaction for credit on this wallet. In debug command line –“getbalance” shows 0

Recreate: Linux Ubuntu 18.04.02 LTS. Minimal Desktop Install. Gnome 3
Wallet: 3.0.9.2 GUI “spectrecoin”
Run wallet as “normal” non root user.
Transfer some spectre to the wallet. They WILL show up. 
Turn on “secured shared memory”

**vi /etc/fstab**
add as last line:
_**tmpfs /run/shm tmpfs defaults,noexec,nosuid 0 0**_

mount it again with **sudo mount –a** or Reboot
run the wallet as normal non root user.

All balance is GONE.
Remove the secure shared memory, remount

Balance shows up.

**Comment by HLXEasy** [comment]
Cannot reproduce this issue.

- Setup vanilla Ubuntu 18.04
- Installed required packages:
  `apt install ca-certificates 
    mc libboost-chrono1.65.1 
    libboost-filesystem1.65.1 
    libboost-program-options1.65.1 
    libboost-thread1.65.1 
    libcap2 
    libevent-2.1-6 
    libqt5webchannel5 
    libtool 
    libseccomp2 
    obfs4proxy 
    qtwebengine5-dev 
    tor 
    wget`
- Installed Aliaswallet v4.3.1
- Added user account
- Downloaded bootstrap archive and extracted it
- Installed Shell-UI
- Put a wallet with some coins onto the machine
- **Start the UI -> all fine, the coins are there**
- Stopped the wallet and shutdown the machine
- Created snapshot as backup
- Restartet the machine
- Changed /etc/fstab as described above
- Reboot
- **Start the UI -> all fine, the coins are there**
