### ISSUE TITLE
Error: Invalid Stealth Address. SPECTRE to XSPEC conversion requires a stealth address.

### ISSUE THREAD

**Issue by cryptomaxsun** [aliascash/alias-wallet-archive#188]
I decided to try how the transfer of coins between Spectrecoin and XCPEC.
Is it possible that I can not send coins from a stealth address to a public one?

In "Wallet > Send > Balance Transfer" I want to move coins from private to public. But if sending the payment I get the answer
I do not use the default addresses, I use new created ones. Converting XSPEC (public) to SPECTRE (private) ran as expected. I can transfer private SPECTRE to the "Default Stealth Address" in "Balance Transfer", and the coins appear in the public XSPEC coin list. I do not understand this behaviour.

From https://bitcointalk.org

**Comment by teknex** [comment]
Behavior as designed. You need also a stealth address when converting SPECTRE to XSPEC.
