### ISSUE TITLE
Integrate the gettxout API call into the code

### ISSUE THREAD

**Issue by aliascash** [aliascash/alias-wallet-archive#2]
Integrate the gettxout API call into the code base for Spectrecoin
<img width="957" alt="screen shot 2018-03-30 at 15 48 26" src="https://user-images.githubusercontent.com/22733129/38141820-de267e46-3431-11e8-9401-c820b060f2ff.png">
This is needed to get XSPEC listed at BarterDEX.

Bounty!

**Comment by Veegold** [comment]
When will this issue be resolved? So that xspec can be listed at barterdex

**Comment by teknex** [comment]
Fixed with V3
