### ISSUE TITLE
1.4.0 beta (Windows 10) Not starting

### ISSUE THREAD

**Issue by din3** [aliascash/alias-wallet-archive#20]
After console startup it crashes before seeing GUI.
Latest command entry before closing automatically:

[500:2336:0517/173624.069:ERROR:broker_win.cc(59)] Error reading broker pipe; The pipe has been ended. (0x6D)

![2018-05-17_17h45_51](https://user-images.githubusercontent.com/38725493/40184969-32999218-59fa-11e8-987e-9978062d37e1.png)

**Comment by aliascash** [comment]
@din3 can you DM me on Discord please to discuss this fault. If you are not on Discord, here is the link: https://discord.gg/ckkrb8m

**Comment by shbli** [comment]
@din3 Could you please download the following 3 dlls that are missing

https://ufile.io/bu75x

Put them in the same folder next to spectre.exe and try again. Let us know how this works for you.

If it fix it we will make sure to ship the new version with it and also update our build instructions to make sure they're always available.

**Comment by din3** [comment]
no effect, problem persists. 

![2018-05-18_08h26_22](https://user-images.githubusercontent.com/38725493/40217414-4710a9c2-5a75-11e8-9419-5c1911788c62.png)

**Comment by shbli** [comment]
@din3 please have a look here

https://github.com/ContinuumIO/anaconda-issues/issues/9142

If that doesn't help I'll get back to you later. This bug is quit similar to what you are looking at.

**Comment by din3** [comment]
I've been trying the DLL's from the link http://download.qt.io/development_releases/prebuilt/llvmpipe/windows/
opengl32sw-64.7z
opengl32sw-64-mesa_12_0_rc2.7z
opengl32sw-64-mesa_11_2_2.7z

There was no effect.
Thats's what the debug.log throws out btw:

[0524/230354.802:WARNING:resource_bundle_qt.cpp(115)] locale_file_path.empty() for locale 
[0524/230355.801:WARNING:resource_bundle_qt.cpp(115)] locale_file_path.empty() for locale

**Comment by shbli** [comment]
New build will be up soon! You can let me know if the same issue occurs. Please wait for the announcement.

Sent from my iPhone

On May 24, 2018, at 1:07 PM, din3 <notifications@github.com<mailto:notifications@github.com>> wrote:


I've been trying the DLL's from the link http://download.qt.io/development_releases/prebuilt/llvmpipe/windows/
opengl32sw-64.7z
opengl32sw-64-mesa_12_0_rc2.7z
opengl32sw-64-mesa_11_2_2.7z

There was no effect.
Thats's what the debug.log throws out btw:

[0524/230354.802:WARNING:resource_bundle_qt.cpp(115)] locale_file_path.empty() for locale
[0524/230355.801:WARNING:resource_bundle_qt.cpp(115)] locale_file_path.empty() for locale

**Comment by din3** [comment]
The new beta is working fine now.
When trying the old beta, it's working flawless as well. So you did some proper job there, sir. TY.
I tried the beta 3 on Win7 as well, as the old beta was crashing there too, but it's working like a charm all over.
