### ISSUE TITLE
Spectrecoin-3.0.14-73b56ca0-RaspbianLight - problem with keys

### ISSUE THREAD

**Issue by Shekelme** [aliascash/alias-wallet-archive#206]
Right after starting the Raspberry with newly-flashed SD card with Spectrecoin-3.0.14-73b56ca0-RaspbianLight image I performed 'apt update' command. It returned the following messages related to public keys:

`pi@raspberrypi:~ $ sudo apt update
Get:1 http://ftp.debian.org/debian stretch-backports InRelease [91.8 kB]
Get:2 http://archive.raspberrypi.org/debian stretch InRelease [25.4 kB]
Get:3 http://raspbian.raspberrypi.org/raspbian stretch InRelease [15.0 kB]
Err:1 http://ftp.debian.org/debian stretch-backports InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7638D0442B90D010 NO_PUBKEY 04EE7237B7D453EC
Get:4 http://raspbian.raspberrypi.org/raspbian stretch/main armhf Packages [11.7 MB]
Reading package lists... Done
W: GPG error: http://ftp.debian.org/debian stretch-backports InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7638D0442B90D010 NO_PUBKEY 04EE7237B7D453EC
E: The repository 'http://ftp.debian.org/debian stretch-backports InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
`
I fixed it with instructions from this page: https://raspberrypi.stackexchange.com/questions/12258/where-is-the-archive-key-for-backports-debian-org

But it could be very nice if all that stuff work right out of the box.

**Comment by HLXEasy** [comment]
@Shekelme Could you provide some more details what you did exactly? I'm unable to get the error fixed as gpg always returned with something like 

> gpg: keyserver receive failed: No data

or 

> gpg: no valid OpenPGP data found.

Any ideas?

**Comment by Shekelme** [comment]
@HLXEasy, unfortunately I have nothing to say beyond the instructions given at the link above...

**Comment by HLXEasy** [comment]
As of 4.3.1 not using backports anymore.
