### ISSUE TITLE
Add support for '-datadir=<folder_path>' parameter

### ISSUE THREAD

**Issue by aliascash** [aliascash/alias-wallet-archive#21]
Most QT-based coins support the usage of the '-datadir=<folder_path>' parameter, XSPEC currently does not. This would allow greater security and the ability to store coins in encrypted containers, keyfiles on isolated hardware such as a USB memory stick.

**Comment by mammix2** [comment]
taking this on.

**Comment by mammix2** [comment]
functionality already exists in XSPEC src. 
https://github.com/spectrecoin/spectre/blob/master/src/util.cpp#L1079-L1110

I havent manually tested for any error yet, can someone tell me what happens when the arg is set ?

**Comment by shbli** [comment]
There was a bug. Fixed and committed linked to that issue
