### ISSUE TITLE
Status icon tooltips offscreen when scrolled down past header text

### ISSUE THREAD

**Issue by ptownsimon** [aliascash/alias-wallet-archive#26]
On any section of wallet, if you can scroll down enough so the header text is hidden (e.g. 'OPTIONS', 'TRANSACTIONS', 'OVERVIEW'), then the status icons' tooltips hover above instead of below, making them unreadable.

Currently using Window 10 64-bit, wallet 1.4.0 Beta2.

**Comment by shbli** [comment]
@ptownsimon please use beta 5. if possible provide screenshot

@spectrecoin please tag the issue for which version to be fixed at.

**Comment by ptownsimon** [comment]
![image](https://user-images.githubusercontent.com/30858254/41077127-26fd0c2c-69d2-11e8-8697-9f70a9227988.png)

Not sure how to tag. Used 1.4.0 Beta 5 Win64. Noticed this issue for at least a few versions.

**Comment by teknex** [comment]
Fixed on develop. Will be released with 2.0.6
