### ISSUE TITLE
Missing include on Fedora 27

### ISSUE THREAD

**Issue by bitcoinx2** [aliascash/alias-wallet-archive#28]
The include path for QWebEngineView is not configured correctly for Fedora 27. The error is:

```
In file included from qt/moc_spectregui.cpp:9:0:
qt/spectregui.h:9:10: fatal error: QWebEngineView: No such file or directory
 #include <QWebEngineView>
```
The missing files are in

- /usr/include/qt5/QtWebEngineWidgets/qwebengineview.h
- /usr/include/qt5/QtWebEngineWidgets/QWebEngineView

so the correct include would be `QtWebEngineWidgets/QWebEngineView`, or alternatively `/usr/include/qt5/QtWebEngineWidgets` must be included on the compiler level separately. The same problem probably also applies to other libraries like QtGui, QtWidgets, QtWebChannel, QtNetwork.

**Comment by shbli** [comment]
@spectrecoin @bitcoinx2 we have successfully compiled on Ubuntu and it works perfectly well over there.

Now if Fidora is a high priority we can fix it for 1.4.0 and if not we can release 1.4.0 and then leave that for 1.4.1 or another release.

@spectrecoin please assign the proper tag to the issue.

**Comment by dragononcrypto** [comment]
I just came across this exact same build error on (L)ubuntu 18.04. So not just Fedora based, more likely to be related to latest stable Linux distros if it builds in an old version of Ubuntu without problems. Personally, I think the best bet is migrate testing to Ubuntu 18.04 LTS, that's what users will be eventually doing due to the upgrade prompting, even if not the best idea in the short-term.

**Comment by bitcoinx2** [comment]
Confirmed on Fedora 28. Ubuntu should not be the assumed default for any release, there are many different Linux distros. I would recommend to test the software on the most common Linux distros before releasing.

**Comment by dragononcrypto** [comment]
The pull request helped, but didn't solve the underlying issue of missing includes for me, unless I'm missing something obvious here. This is after a fresh git pull and re-build, Ubuntu 18.04 again. 

```
In file included from qt/moc_spectregui.cpp:9:0:
qt/spectregui.h:8:10: fatal error: QMainWindow: No such file or directory
 #include <QMainWindow>
```
