### ISSUE TITLE
1.4.0 Beta can not generate a new address from the GUI

### ISSUE THREAD

**Issue by ghost** [aliascash/alias-wallet-archive#29]
1.4.0 Beta can not generate a new address from the GUI.
javascript: addAddress () does not seem to be working.
The address book's new address also does not work.

Currently using Window 10 64-bit, wallet 1.4.0 Beta4.

**Comment by aliascash** [comment]
I have experienced the same problem

**Comment by shbli** [comment]
Thank you for reporting the bug and helping in the test of the 1.4.0 beta. I'm about to finish this now! @Senioris then you can try again in the latest build and if it happens again reopen the ticket.

**Comment by shbli** [comment]
Hey @Senioris you may try beta 5

https://www.dropbox.com/sh/ggybk70skjqy8e0/AAAI-58wHcwo_bfwkz0LlNm7a?dl=0

If you like to wait for the official release then feel free to do that. But we will appreciate you trying out beta 5 and let us know if it fixes the issues.

**Comment by ghost** [comment]
I confirmed that it has been fixed. Thank you.
