### ISSUE TITLE
1.4-beta4 - address book 'lookup' doesn't work

### ISSUE THREAD

**Issue by aliascash** [aliascash/alias-wallet-archive#30]
When I use an address thats in the address book, the wallet doesn't look it up when entered in the 'pay to" field". This can be considered a security feature. If I want to send 1000 XSPEC to an exchange I copy and paste the address from the exchange and into my wallet and I see that it matched the one I have in my address book and have used before and I know it's the correct address

**Comment by shbli** [comment]
@spectrecoin need more details about this one please. It may be the case that it is related to the other address issues. I'm able to look up address by address/label for now.

**Comment by aliascash** [comment]
I copy an address from my receive list: SR9z2GmWjBPUGTXPoTwT1qjky7MTti9um1 and the label for this address is 'CONSOLIDATION'
<img width="976" alt="screen shot 2018-06-06 at 20 35 54" src="https://user-images.githubusercontent.com/22733129/41061022-4197c3d2-69c9-11e8-81fb-42b50fe272ee.png">
I then enter the same address: SR9z2GmWjBPUGTXPoTwT1qjky7MTti9um1 in the 'pay to' field in the send dialog box:
<img width="811" alt="screen shot 2018-06-06 at 20 36 56" src="https://user-images.githubusercontent.com/22733129/41061083-6b6bd2d4-69c9-11e8-91fe-7596212ffcbd.png">
When pressing TAB to go to the next field or I click in another field, the software automatically fills in the 'enter a label' field as the label is already set:
<img width="913" alt="screen shot 2018-06-06 at 20 38 24" src="https://user-images.githubusercontent.com/22733129/41061142-9800980c-69c9-11e8-811c-2793545f2e12.png">
This does not work on 1.4-beta5

**Comment by shbli** [comment]
@spectrecoin Roger that. Now it is very clear. Looking into it.

**Comment by shbli** [comment]
@spectrecoin wait for the new release.
