### ISSUE TITLE
Spectre-beta-5: Menu > 'Tools' > 'Chain Data' does not display the anon token balances

### ISSUE THREAD

**Issue by aliascash** [aliascash/alias-wallet-archive#32]
Menu > 'Tools' > 'Chain Data' is meant to display the same as the 'anoninfo' call in the console:
<img width="784" alt="screen shot 2018-06-06 at 19 57 08" src="https://user-images.githubusercontent.com/22733129/41059407-65364282-69c4-11e8-954e-1a0efcf2aff1.png">
<img width="1296" alt="screen shot 2018-06-06 at 19 55 23" src="https://user-images.githubusercontent.com/22733129/41059414-69150848-69c4-11e8-88c6-118d7740db19.png">
However, the beta-5 does not display this. Below is the way it is meant to display from 1.3.8:
<img width="1233" alt="screen shot 2018-06-06 at 20 02 50" src="https://user-images.githubusercontent.com/22733129/41059515-aebd1d54-69c4-11e8-80b8-1db565aad5a3.png">

**Comment by shbli** [comment]
@spectrecoin looking into it
