### ISSUE TITLE
1.4 crashed when unlocking from the command line / console OSX

### ISSUE THREAD

**Issue by aliascash** [aliascash/alias-wallet-archive#38]
<img width="340" alt="screen shot 2018-06-10 at 21 05 29" src="https://user-images.githubusercontent.com/22733129/41205790-07bc38a6-6cf2-11e8-9882-46b16d4193b5.png">

When unlocking the wallet for a period of time from the console the wallet crashes on executing the command.

**Comment by teknex** [comment]
#65 same issue

**Comment by teknex** [comment]
see comment in #65, 2.0.6 will show error message instead crash when rpcserver is not running
