### ISSUE TITLE
JS error when using the function "Suggest Ring Size" when sending SPECTRE

### ISSUE THREAD

**Issue by aliascash** [aliascash/alias-wallet-archive#39]
This relates to sending anonymous SPECTRE coins from your private balance.
<img width="993" alt="screen shot 2018-06-10 at 21 08 33" src="https://user-images.githubusercontent.com/22733129/41205834-8fab1ebc-6cf2-11e8-98c6-d87751df9cf0.png">
Once you enter a stealth address to send to and the amount you wish to send and click the button 'Suggest Ring Size', the wallet frequently returns an error: 
<img width="720" alt="screen shot 2018-06-10 at 21 08 46" src="https://user-images.githubusercontent.com/22733129/41205832-8b9def3e-6cf2-11e8-8dff-ca19b317fbaa.png">

However, if you manually send using 'sendanontoanon' in the console the transaction is created with no issues and the anonymous coins are split and sent as expected.
<img width="755" alt="screen shot 2018-06-10 at 21 20 21" src="https://user-images.githubusercontent.com/22733129/41205909-3c829ede-6cf4-11e8-9e4e-82a5da7e3315.png">
https://chainz.cryptoid.info/xspec/block.dws?708450.htm

There appears to be a fault in the way the JS code checks for ring sizes and owned anon outputs. The algo for splitting and sending anon coins in wallet.cpp appears correct but the JS code does it's own checks that somehow gives a different outcome.

https://github.com/spectrecoin/spectre/blob/2bdee4b8df39e55916e56762f83b88c94f5bf70a/src/qt/res/assets/js/pages/send.min.js#L141

**Comment by shbli** [comment]
Looking into this one!

**Comment by shbli** [comment]
@spectrecoin this is closed. Let me know if that works! if not reopen and comment.
