### ISSUE TITLE
Timeout waiting for onion hostname

### ISSUE THREAD

**Issue by dragononcrypto** [aliascash/alias-wallet-archive#4]
Built from source in Ubuntu 17.04 (Linux)

Let me know if you want bedug.log or tor.log data. This issue was previously documented in the XSPECOfficial repository on February 9th and has yet to be resolved as far as I understand.

I was advised by one of your devs /helpers in discord to shutdown and restart the wallet but this does not solve the problem. Thanks in advance for solving this issue in a future release.

Please note, I tested the Windows packaged wallet through WINE in Linux and do not have this issue, therefore I would assume this issue is when building from source, or exclusive to Linux. If I find a solution in the meantime I will make a pull request. Please also consider an AppImage.

**Comment by aliascash** [comment]
Thank you for your input. We will look at this. Can you come to our Discord server to chat? Can you post the debug files here?

**Comment by shbli** [comment]
@dragononcrypto any chance you try the latest version CLI?

Post to us the debug files

it may be an issue that Tor is not working. I can guide you on how to test out Tor

**Comment by teknex** [comment]
Probably fixed with latest V2 builds.
