### ISSUE TITLE
Error launching when using the Russian version of Windows Server 2016

### ISSUE THREAD

**Issue by vovannovig** [aliascash/alias-wallet-archive#40]
There is a mistake in the new wallet.
If I use the Windows 20016 server in Russian, the wallet can not receive an error because of the user name.
The old version 1.3.5 works fine.

![fffff](https://user-images.githubusercontent.com/40199379/41281513-3f9ab1a0-6e3a-11e8-89ac-1a43043bb057.jpg)

**Comment by LeoBitman** [comment]
Version 2.0.4.3 solves this problem, there is already a positive test on a virtual machine.

**Comment by teknex** [comment]
fixed with 2.0.5
