### ISSUE TITLE
Copy / Paste add characters

### ISSUE THREAD

**Issue by Marvel63** [aliascash/alias-wallet-archive#42]
In Transactions screen, I select one, right-click and choose "copy transaction ID"

![image](https://user-images.githubusercontent.com/5469297/41378274-e166c184-6f5e-11e8-821b-e82f0ce05348.png)

The transaction ID is this one 

![image](https://user-images.githubusercontent.com/5469297/41378123-5c1ab936-6f5e-11e8-8c0b-463def3d6e04.png)

Then I paste in my Block explorer the characters "-000" at the end of the address
![image](https://user-images.githubusercontent.com/5469297/41378230-b95025a0-6f5e-11e8-95e1-a68fdc015c70.png)

Same behavior if private or public transactions

**Comment by Marvel63** [comment]
no feedback?

**Comment by teknex** [comment]
Fixed with 2.0.5
