### ISSUE TITLE
Investigate error message: "The transaction was rejected......"

### ISSUE THREAD

**Issue by aliascash** [aliascash/alias-wallet-archive#44]
Can the exact parameters / criteria for this error message be investigated. When and why does this error message occur?

https://imgur.com/e9SDaSa

https://github.com/spectrecoin/spectre/blob/738567c0d3c34e663e5859e23a29b06aa1595406/src/wallet.cpp#L2434

**Comment by shbli** [comment]
@spectrecoin possible to send me the logs? of when this happens. It is not always one case there's multiple cases and I can see them written to the logs.

**Comment by teknex** [comment]
Technically this error happens when a TRX is not accepted by other nodes. The concrete problem is your case cannot be evaluated. I close this issue for now.
