### ISSUE TITLE
GUI / JS: 'PRIVATE' balance / transaction history doesn't update with incoming private transactions when wallet is locked

### ISSUE THREAD

**Issue by aliascash** [aliascash/alias-wallet-archive#45]
When receiving incoming 'PRIVATE' to 'PRIVATE' transaction using a stealth address the incoming transactions are shown as 'SENT' in the transaction list w/ an amount of 0.00000000 although the transaction was in fact for 50 SPECTRE.

The 'PRIVATE' balance total does not update as well.

<img width="512" alt="screen shot 2018-06-17 at 17 58 39" src="https://user-images.githubusercontent.com/22733129/41523339-8e0c6266-72d1-11e8-8895-60e7551abef7.png">

When you then unlock the wallet:

<img width="1017" alt="screen shot 2018-06-17 at 17 58 58" src="https://user-images.githubusercontent.com/22733129/41523475-01c85bb0-72d2-11e8-8d6b-8471731756c2.png">

The 'PRIVATE' balance total is updated but the transaction list is not. You need to restart the wallet for the transaction list to be updated:

<img width="469" alt="screen shot 2018-06-17 at 18 06 29" src="https://user-images.githubusercontent.com/22733129/41523515-2c99f3c6-72d2-11e8-8f37-334292715a7a.png">

The transaction is then shown correctly. This may be an issue with the GUI/JS not being able to access the stealthaddress 'spend secret' and  'Scan Secret' to read PRIVATE-2-PRIVATE transactions when the wallet is locked.

**Comment by shbli** [comment]
I can see it too! Looking into it.
