### ISSUE TITLE
crash from dll errors when creating new address

### ISSUE THREAD

**Issue by beachguynf** [aliascash/alias-wallet-archive#49]
this is the v1.4 posted on June 21.
I uploaded in the group.....but it must have been overlooked.
![v1 4_event](https://user-images.githubusercontent.com/40498706/41788076-6dc70a7a-7618-11e8-92e4-7dda22353c9a.png)
this computer is older but runs v1.3.5 just fine

**Comment by teknex** [comment]
Fixed with 2.0.4.2
