### ISSUE TITLE
1.4.0 wallet win64

### ISSUE THREAD

**Issue by dwarfman92** [aliascash/alias-wallet-archive#51]
I am getting

js: Uncaught TypeError: Cannot read property 'classList' of null

and 

js: Uncaught ReferenceError: prevPage is not defined

What are these errors?

**Comment by aliascash** [comment]
What version of the wallet are you using?

**Comment by dwarfman92** [comment]
Latest release, 1.4.0 windows 10

**Comment by teknex** [comment]
@dwarfman92 Please try again with 2.0.5.

**Comment by teknex** [comment]
Closed because of inactivity and probably fixed in 2.0.5.
