### ISSUE TITLE
Slow blockchain sync speed

### ISSUE THREAD

**Issue by aliascash** [aliascash/alias-wallet-archive#52]
This is an issue that needs to be addressed for v.1.5 of Spectrecoin - it takes too long for a new user to download the Spectre blockchain and this will deter users from using the software. We need to dramatically increase the sync speed for new users.

**Comment by teknex** [comment]
Informations regarding data organization for bitcoin: https://en.bitcoin.it/wiki/Data_directory

The essential blockchain data without any private data is stored in:
1. File blkxxxx.dat: blockchain data in net format
2. Folder txleveldb:  a database containing the indexed transactions

If you have an empty Spectre data directoy and put the  blkxxxx.dat and txleveldb inside. on startup the Application scans all trx with the private keys stored in wallet.dat.
On a moderate fast PC this takes under 2 min. The application considers the blocks in blkxxx.dat as trustworty and does not validate them.

A zip file with the data is about  530 MB

**Comment by HLXEasy** [comment]
See GitHub repo https://github.com/spectrecoin/spectrecoin-blockchain-bootstrap, which is used by Jenkins job http://ci.spectreproject.io/job/Spectrecoin/job/spectrecoin-blockchain-bootstrap/ to create zip archive https://github.com/spectrecoin/spectre/releases/download/v2.0.7/Spectrecoin-Blockchain.zip.
