### ISSUE TITLE
Wallet Will Not Sync

### ISSUE THREAD

**Issue by elmojocelery** [aliascash/alias-wallet-archive#54]
![2018-06-27 1](https://user-images.githubusercontent.com/40644478/42004035-bfc950ca-7a33-11e8-8a97-c02ef747f068.png)

First, when the wallet opens this window opens as well and if you kill this window the wallet closes.
Second, although I have 35 active connections, my wallet is not syncing.

**Comment by aliascash** [comment]
What version of the wallet are you using and what OS?

**Comment by teknex** [comment]
@elmojocelery  Please try again with 2.0.5. if you have a problem please ask us in the discord help channel.

**Comment by teknex** [comment]
Closed because of inactivity and probably no error in Spectrecoin.
