### ISSUE TITLE
wallet immediately close after walletpassphrase via console Win 8.1

### ISSUE THREAD

**Issue by igilepic** [aliascash/alias-wallet-archive#65]
I dwld the newest qt wallet 2.0.4.2 and try to find out my private key via console with dumpprivkey

wallet is encrypted and currently locked on my win 8.1

1. walletpassphrase <wpassphr> 60
then the wallet immediately close

FYI the balance is 0, and before I withdrawl my coins from cryptopia I wish to have this informations

**Comment by teknex** [comment]
Test:
- walletpassphrase 1234 60
- dumpprivkey tCG84kzKsWNh4tJFpSvVFtn67FZbWAiATy

Works with 2.0.5 and balance > 0 and balance == 0 for debugger version but not release version.

**Comment by teknex** [comment]
@shbli walletpassphrase works when in debugger, seems like a NDEBUG related problem you had before. Can you check this?
Maybe related to #27

**Comment by shbli** [comment]
@teknex Looking into this

**Comment by shbli** [comment]
@teknex @igilepic test out the code I just committed on develop branch and let me know!

I'm closing the issue now but open it again if the issue arise again.

Not related to #27

**Comment by igilepic** [comment]
Sorry, but Im not a programmer, so what exactly should I do to test it?

**Comment by teknex** [comment]
The rpc server is needed to lock the wallet after the specified time
With the current fix, when you don't have server active and you return the error message, the wallet is already unlocked

**Comment by teknex** [comment]
@igilepic The function does work already. dumpprivkey needs the wallet to be unlocked. You can do this by

- Unlock the wallet via UI. `Wallet Encryption > (Un)lock Wallet`  (take care to uncheck the 'for staking only' box
- Start the wallet with the `-server` option to activate the RPC server. (RPC server is internally needed to lock the wallet after the specified time)
