### ISSUE TITLE
Transaction ID in transaction detail dialog: link behavior error

### ISSUE THREAD

**Issue by teknex** [aliascash/alias-wallet-archive#69]
- Click on the highlighted Transaction ID has no effect
- If "Follow Link" in the context menu is selected, the block explorer page is opened in the wallet directly and multiple browser tabs are opened in the external browser.

=> Click on transaction ID and context action follow link should open one external page showing the TRX in the blockexplorer

![image](https://user-images.githubusercontent.com/16650998/43617328-b6ec5e0c-96c1-11e8-857b-022175200f7c.png)

**Comment by shbli** [comment]
@teknex looking into this

**Comment by shbli** [comment]
Issue fixed. QtWebEngine does not support target=blank so have to remove that from our HTML

**Comment by teknex** [comment]
There is still some problem: when you choose 'follow link' from the context menu, the block explorer page is opened in the wallet. I think this is a security critical problem, we cannot ever load the HTML/JS of some external site in our wallet.

**Comment by teknex** [comment]
Prevent default context menu with browser actions.
