### ISSUE TITLE
Consider integration of OBFS4 directly in XSPEC wallet

### ISSUE THREAD

**Issue by aliascash** [aliascash/alias-wallet-archive#7]
Consider the integration of OBFS4 directly in the XSPEC wallet, without the need to download additional software. For activation, it should be enough to define the OBFS4 bridges in the spectre wallet settings to activate and use and the wallet could display and indicator that OBFS4 has been activated.

**Comment by teknex** [comment]
With release 2.1.0, there is now a release for Mac and Windows with preconfigured OBFS4 bridges
