### ISSUE TITLE
[2.0.6.0-g] Wrong fee calculation when transfer from private to public

### ISSUE THREAD

**Issue by Marvel63** [aliascash/alias-wallet-archive#75]
I tried to transfer all my XSPEC from my private (49.95 coins) to my public wallets. 
Tried 49.95 with ring size 16, got an error message saying there is a 0.01 fee. Fine, tried 49.94, message now is 0.02 fee. Tried 49.93, message is 0.03. Stopped here.
Find below the screenshots

![image](https://user-images.githubusercontent.com/5469297/43945209-bf64865c-9c81-11e8-9d19-9785da281acc.png)
![image](https://user-images.githubusercontent.com/5469297/43945225-c8dd97be-9c81-11e8-800a-d2e402fec404.png)
![image](https://user-images.githubusercontent.com/5469297/43945230-cf0e2054-9c81-11e8-8fdf-a353311e6586.png)
![image](https://user-images.githubusercontent.com/5469297/43945235-d3fe2370-9c81-11e8-954d-c6c22459c028.png)
![image](https://user-images.githubusercontent.com/5469297/43945243-d92cf5c4-9c81-11e8-9dfd-7e42b8b4a6ac.png)

**Comment by teknex** [comment]
Improved behavior, but could not entirely fix it. The dynamic nature of the fees in combination with the random selection algorithm of ATXOs makes it difficult.

**Comment by teknex** [comment]
fixed with 2.0.6
