### ISSUE TITLE
MacOS v2.0.4 wallet not working

### ISSUE THREAD

**Issue by AlvinChipmunk1** [aliascash/alias-wallet-archive#78]
Hello community! I was using the v2.0.4 wallet on my Mac High Sierra during the last two weeks. Everything was fine, the download, the wallet never crushed, staking was perfect and so on. Suddenly yesterday it stopped syncing, I thought maybe an internet issues where I am living. After an hour nothing changed so I closed the wallet and tried to restart-->error "the program Spectre wasn't able to open". The I did a restart on my computer-->still the same. Then I downloaded an older version 1.3.5 which I had very good experiences with-->everything was fine (it is still running right now). After that I tried to download the v2.0.4 again from GitHub-->I was able to download, it also finished the download but then I wasn't able to open it. When I drag it to the application folder or open it through the Finder it shows a gray spectre symbol, error message "file is damaged or incomplete". 

Can anybody help me with that issue? Today I tried again to download it, same issue. I will also post two screenshots of my console during that progress of trying to start the downloaded file.

Thank you community!
![bildschirmfoto 2018-08-14 um 11 04 12](https://user-images.githubusercontent.com/42382687/44100640-ce82206a-9fe5-11e8-81a3-fb44c1d9441a.png)
![bildschirmfoto 2018-08-14 um 11 04 23](https://user-images.githubusercontent.com/42382687/44100641-cebcfcf8-9fe5-11e8-8de6-c789a80322bc.png)

**Comment by teknex** [comment]
MacOS error: -67062 indicates a possible security violation error. Some users could solve this for other applications with a clean install.

**Comment by AlvinChipmunk1** [comment]
you mean of the whole computer?

**Comment by teknex** [comment]
No only of the application: uninstall / reinstall. This might help you: https://www.cnet.com/how-to/how-to-install-unidentified-app-on-a-macbook/

**Comment by AlvinChipmunk1** [comment]
thank you, but this doesn't help. I already had my settings like this. This is why I was able to download v2.0.4 two weeks ago and run it without any issues UNTIL yesterday, I don't know what suddenly changed?!

**Comment by AlvinChipmunk1** [comment]
downloading older versions is also no problem at the moment, ONLY v2.0.4

**Comment by AlvinChipmunk1** [comment]
Trying to open the "damaged" file of v2.0.4 leads to following console message
--->LSOpenFromURLSpec(file:///Applications/spectre%20Kopie.app/) failed with -10827

**Comment by shbli** [comment]
@AlvinChipmunk1 so it was working but now stopped working?

Where did you see that error message 
--->LSOpenFromURLSpec(file:///Applications/spectre%20Kopie.app/) failed with -10827

Write us more details. Redownload the wallet and try again as well.

**Comment by AlvinChipmunk1** [comment]
I saw that error message in the console. I also tried several times to download it again but I still get the same message. It seems to me that somehow the computer recognizes the file as some kind of malware?! Is that possible? And as a result of this I cannot open the file because it is damaged?

No, for two days now it is not possible for me to run v2.0.4
Thank you!

**Comment by shbli** [comment]
@AlvinChipmunk1 Can you post another screenshot? for that error message.

**Comment by shbli** [comment]
I'm trying the one on GitHub. Downloading it now

**Comment by AlvinChipmunk1** [comment]
I switched off the firewall to what happens after downloading. I will send you another one soon!

**Comment by AlvinChipmunk1** [comment]
I also download from GitHub

**Comment by AlvinChipmunk1** [comment]
I FIGURED IT OUT! It was the Firewall! But it is not good to have it switched off all the time. what can I do?

**Comment by AlvinChipmunk1** [comment]
Now v2.0.4 is running BUT Firewall is switched off

**Comment by shbli** [comment]
Try to allow SpectreCoin to use these ports
9089
37347
36657

**Comment by AlvinChipmunk1** [comment]
I am not sure how to do it: 1. open terminal 2. enter: sudo pfctl -vnf /etc/pf.conf ?? and then?
I am not really into tech, sorry

**Comment by shbli** [comment]
@AlvinChipmunk1 

https://www.howtogeek.com/248836/how-to-allow-apps-to-communicate-through-your-macs-firewall/
