### ISSUE TITLE
Consider minimum coin age of 8 hours for staked coins in UI.

### ISSUE THREAD

**Issue by teknex** [aliascash/alias-wallet-archive#79]
There is an inconsistency between the algo selecting and verifying the coins for staking, and the code showing the staked balance. The code showing the balances in the UI, does not consider mature time of 8 hours.

**Comment by teknex** [comment]
Staked coins (coinstake) maturing situation:

for a staked coin to be able to stake again, the coinstake TRX must be
1. 288 blocks deep in chain
2. 8 hours old

but the 8 hours rule does NOT apply for spending and
is NOT considered in the UI (PUBLIC/STAKED) **but in the staking weight**

According the PoSv3 algo reference we have, the TRX time maturing check was removed in PoSv3. Superflous code in the Spectrecoin codebase indicates that considering of the TRX time for staking is probably an obmission when PoSv3 was implemented.

**Comment by LeoBitman** [comment]
Good observation, it is verified exactly in the operation of the wallet,
and solve a **frequent question**:
**Why is my weight in the network less than my amount of public coins?**
Now  well answered with this that you observed: 288 blocks AND 8 hours.
(the 288 blocks only need ~ 5 hours)
