### ISSUE TITLE
Replace QTWebKit with QTWebEngine for the XSPEC GUI

### ISSUE THREAD

**Issue by aliascash** [aliascash/alias-wallet-archive#8]
QTWebKit has been discontinued and has been succeeded by QTWebEngine. An upgrade to QTWebEngine will allow more stable builds.

**Comment by aliascash** [comment]
being worked on by https://github.com/shbli

**Comment by aliascash** [comment]
- Completed port from QtWebKit to QtWebEngine
- Setup build process on Windows (Incomplete)
- Setup build process on Ubuntu 
- Start a new branch for porting the build process from Autotools/Automaker to QMake (Cross platform using Qt SDK)
- Research and look up different build process in progress

**Comment by Veegold** [comment]
Wow this is awesome one of the things that were lacking before

**Comment by aliascash** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Updated GUI using QTWebEngine](https://trello.com/c/ZUrcrmAR/1-updated-gui-using-qtwebengine)

**Comment by aliascash** [comment]
The port from QT WebKit to WebEngine has been completed
